apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          image: azbcww/web@sha256:c7cabd2f848ab4e5e6076f812ab16d1ccb5ca406f9ca0c762daf588422e2418d
