apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          image: azbcww/web@sha256:ba605b67fc09e63c098924c0eaf283e72504ba4db9334cfc547f080866314c1f
